### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar-tools#9]
I personal think that `sonar-tools` is a bit misleading, maybe `testing-ground`?

@sonarwhal/contributors Thoughts?

**Comment by molant** [comment]
It depends on what ends up here. If we add the sitemap script or recipes for something else (basically anything that is interesting but only takes 1-2 files) I don't think the name will be accurate.

**Comment by alrra** [comment]
> It depends on what ends up here. If we add the sitemap script or recipes for something else (basically anything that is interesting but only takes 1-2 files) I don't think the name will be accurate.

Then, maybe just go with something such as: `tools`or `misc-tools` ?

**Comment by sarvaje** [comment]
I like `tools`

**Comment by molant** [comment]
Let's go with `tools` then.
